name: likee_clone
description: Video Streaming App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  line_icons:
  streaming_shared_preferences: ^1.0.1
  http: ^0.12.2
  font_awesome_flutter: ^8.11.0
  flutter_icons: ^1.1.0
  #page_transition: ^1.1.7+3
  video_player: ^0.10.8+1
  getflutter: ^1.0.11
  flutter_spinkit: ^4.1.2+1
  hexcolor: ^1.0.6
  after_layout: ^1.0.7+2
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.5.0

  #preload_page_view: ^0.1.4
  #cloud_firestore: ^0.14.4
  #cached_video_player: ^1.0.3
  #gallery_saver: ^2.0.1
  #camera: ^0.6.2+1
  #visibility_detector: ^0.1.5
  #uuid: ^2.2.2
  #path_provider: ^1.6.24

  infinite_listview: ^1.0.1+1
  infinite_scroll_pagination: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  fijkplayer: ^0.8.7
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "Likee"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo/likee.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/app-logo/
    - assets/images/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700